# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d1730b77d10b91580acb84a75f56185892c5e7e7e6c8f878b31448a15bfe8f3fe2a34f89865b126637dbddefa7164aefc92380c5f72855bf4e795b396eb4962

test:
  secret_key_base: 562228dccc8b6b4709e79aa5b7bc5cfbf070aa54b4a9de244506ab2d4cf6c993f2e8c6023011975a0fba02aade3282d964e6df46d469f19ae10e5295fcc8ef29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
